FROM php:8.3-apache

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql

RUN a2enmod rewrite

# Copy front files for FO
COPY front/ /var/www/html/

# FO specific Apache config
COPY docker/vhost-fo.conf /etc/apache2/sites-available/000-default.conf

RUN chown -R www-data:www-data /var/www/html
